### ISSUE TITLE
spirit.c:125: warning

### ISSUE THREAD

**Issue by AntoninoTarantino** [posixninja/spirit-linux#2]
Hello, as you can see during the compilation of Spirit we receive this warning:

spirit.c:125: warning: passing argument 5 of ‘afc_file_write’ from incompatible pointer type

This warning can be fixed changing the type of the "w" variable, in send_over function, from size_t to uint32_t, same thing for the "r" variable. Hope this'll help to make it better. =)

**Comment by posixninja** [comment]
hmm... weird, I don't get those warnings, but I probably don't have my warning level set high enough.  I went ahead and fixed it anyways, thank you again
