### ISSUE TITLE
Noobie problem..

### ISSUE THREAD

**Issue by Frank-Leach** [posixninja/spirit-linux#7]
I tried to do this in terminal, but failed. Is it possible you can list it exactly as it needs to be entered in terminal, word for word and line for line?
I'm sorry..i use linux mint 7 for years and have just never needed to use terminal. The purchase of a cursed itouch yesterday has turned things up in the air. 
I got on alright with the type that was in light grey..then stuff became unreconisable by terminal. Some help for a noob would be appreciated. Thanks..

**Comment by posixninja** [comment]
make
./spirit

**Comment by Frank-Leach** [comment]
ok..so is this how it should be in terminal? I did try this, to no avail...;
~ $ make./spirit
The result was ; no such file or directory.(i also tried ~$ ./spirit -no luck either)
Sorry if i am wrecking your head here..maybe i need to research commands some more before tackling stuff like this?

**Comment by Frank-Leach** [comment]
update..i saw what you meant. tried that as written ~$ make ./spirit.
The result? "make: **\* No rule to make target `spirit'.  Stop."
Sorry to be a pest, tell me to but linux for dummies, its prob what i need anyway

**Comment by posixninja** [comment]
it's 2 different commands

make; (then press enter)
./spirit; (then press enter)

(but without the (then press enter) stuff ;))

**Comment by posixninja** [comment]
or if you still can't get it, pakizip has a precompiled version with a gui at http://kerneldelmondo.netsons.org/spirit-ui_0.1_i386.deb

**Comment by AntoninoTarantino** [comment]
I'd write a README with all the steps to follow and I'd put somewhere, maybe a text in the wiki should be fine, seen that these are _not issues_.
