### ISSUE TITLE
ERROR: Unable to find device in maps.plist

### ISSUE THREAD

**Issue by rykerwilliams** [posixninja/spirit-linux#8]
Error when running spirit against my ipod touch 2g

**Comment by rykerwilliams** [comment]
Running 3.1.3 firmware.

**Comment by rykerwilliams** [comment]
No, scratch that, it was running 2.2.1. I am updating now.

**Comment by posixninja** [comment]
works with 3.1.2 and 3.1.3 only

**Comment by ardevd** [comment]
Im getting that error when trying to jailbreak my iPad 3.2.2 as well!

Note: just noticed that 3.2.2 is not breakable yet >_<
